<a href="https://colab.research.google.com/github/anishkr-sahu/Genai/blob/main/Genai_day_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- word
- documents
- corpus
- vocabulary

In [ ]:
# Bag of words : it counts the frequency of occurrence of unique words in the document
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame({"text": ["people watch dswithbappy",
                            "dswithbappy watch dswithbappy",
                            "people write comment",
                            "dswithbappy write comment"],
                   "output": [1,1,0,0]})
df

,text,output
0,people watch dswithbappy,1
1,dswithbappy watch dswithbappy,1
2,people write comment,0
3,dswithbappy write comment,0


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
bow = cv.fit_transform(df["text"])
print(cv.vocabulary_)


{'people': 2, 'watch': 3, 'dswithbappy': 1, 'write': 4, 'comment': 0}


In [ ]:
bow.toarray()

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]])

In [ ]:
# n- grams : take n words as a one word
cv = CountVectorizer(ngram_range=(2,2))
bow = cv.fit_transform(df["text"])
print(cv.vocabulary_)

{'people watch': 2, 'watch dswithbappy': 4, 'dswithbappy watch': 0, 'people write': 3, 'write comment': 5, 'dswithbappy write': 1}


In [ ]:
bow.toarray()

array([[0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 0, 0, 0, 1]])

In [ ]:
# TF-IDF : Term frequency ( appearence) - Inverse document frequency ( importance check of word)
# koi word ki kitni importancce hai uss document mai
# tf = no of term appearnce in document/no of unique words
# idf = log(total documents/number of words containing that word)


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid= TfidfVectorizer()

In [ ]:
arr = tfid.fit_transform(df["text"])

In [ ]:
arr.toarray()

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [17]:
# word2Vec
sentences = [
    ["nlp", "is", "Interesting"],
    ["machine", "learning","is","powerful"],
    ["deep","learning","is","advanced"],
    ["nlp","and","machine","learning"],
    ["i","love","studying","nlp"],
    ["students","prefer","machine","learning"],
    ["nlp","helps","in","text","processing"],
    ["learning","new","'topics","is","fun"],
    ["artificial","Intelligence","is","future"]
]

In [18]:
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 44.5 MB/s eta 0:00:00


In [24]:
from gensim.models import Word2Vec
# define model & training
model = Word2Vec(
    sentences,
    vector_size= 50,
    window=3,
    min_count=1,
    workers=700
)
print("vector for nlp")
print(model.wv['nlp'])
print("\nwords similar to nlp")
print(model.wv.most_similar('nlp'))

vector for nlp
[-0.0172385   0.00733054  0.01037987  0.01148296  0.0149314  -0.01233623
  0.00221015  0.01209577 -0.00568088 -0.01235019 -0.00081942 -0.01673954
 -0.01119835  0.01421161  0.00670445  0.01445334  0.01360277  0.01506222
 -0.00757942 -0.00112307  0.00469667 -0.00903924  0.01677942 -0.01971529
  0.01352862  0.00583053 -0.00986593  0.00879769 -0.00347934  0.01342519
  0.01993117 -0.00872741 -0.00120124 -0.0113933   0.00770338  0.00557218
  0.0137809   0.01220248  0.01908012  0.01854657  0.01579589 -0.0139788
 -0.01831177 -0.00071232 -0.00620046  0.01578948  0.01188056 -0.00309005
  0.00302338  0.0035778 ]

words similar to nlp
[('i', 0.19606032967567444), ('future', 0.1655939370393753), ('text', 0.15516488254070282), ('students', 0.1438673436641693), ('Interesting', 0.14380493760108948), ("'topics", 0.13940690457820892), ('learning', 0.1266929656267166), ('processing', 0.1212104856967926), ('studying', 0.1051679477095604), ('artificial', 0.08864957094192505)]


In [25]:
# vocabulary
print("Vocabulary: ")
print(model.wv.index_to_key)

Vocabulary: 
['learning', 'is', 'nlp', 'machine', 'future', 'Intelligence', 'artificial', 'fun', "'topics", 'new', 'processing', 'text', 'in', 'helps', 'prefer', 'students', 'studying', 'love', 'i', 'and', 'advanced', 'deep', 'powerful', 'Interesting']


In [30]:
# sentence to vector
import numpy as np
def sent_vec(sentence):
  words = sentence.lower().split()
  vectors= []
  for word in words:
    if word in model.wv:
      vectors.append(model.wv[word])
  return np.mean(vectors,axis=0)

sentence = "nlp is interesting"
vec = sent_vec(sentence)
print(vec)

[-0.01678396  0.00816661  0.00104949  0.0065669   0.01597418 -0.01063185
  0.00562576 -0.00074555 -0.00638919  0.00323263 -0.00198961 -0.00804655
 -0.00974465 -0.0005832   0.00184576  0.00969305  0.00590767  0.01306519
 -0.00653102  0.00169781  0.00780804  0.00383027  0.00693177 -0.01907376
  0.01113785  0.0034838   0.0025144   0.00358176 -0.00437892 -0.00204675
  0.00910789 -0.00153457  0.00480857  0.00136307 -0.00185829  0.00464772
  0.01298595  0.00130275  0.00642487  0.01607393  0.00952986 -0.00679925
 -0.00567901 -0.00013747  0.00652282  0.01295804 -0.00298484 -0.00859122
  0.00241311  0.00818836]


In [38]:
# consine similarity score
from sklearn.metrics.pairwise import cosine_similarity

s1 = sent_vec("nlp is interesting")
s2 = sent_vec("machine learning is interesting")

similarity = cosine_similarity([s1],[s2])
print("sentence similarity\n")
print(similarity[0][0])

sentence similarity

0.31536606
